# kube-prometheus-stack Helm values for Jenkins monitoring stage
grafana:
  enabled: true
  adminUser: admin
  adminPassword: admin
  service:
    type: NodePort
    nodePort: 30300

prometheus:
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false
    serviceMonitorNamespaceSelector: {}
    podMonitorNamespaceSelector: {}

  service:
    type: NodePort
    nodePort: 30090
