apiVersion: v1
kind: Service
metadata:
  name: app-service
  namespace: default
  labels:
    app: student-webapp
spec:
  type: NodePort
  selector:
    app: student-webapp
  ports:
    - name: http
      port: 3000
      targetPort: 3000
      nodePort: 30030
      protocol: TCP
